// POST Body 中需要 email 字段
export const ERR_BODY_EMAIL_REQUIRED = 'ERR_BODY_EMAIL_REQUIRED';

// POST Body 中需要 password 字段
export const ERR_BODY_PASSWORD_REQUIRED = 'ERR_BODY_PASSWORD_REQUIRED';

// 验证码超时失效
export const ERR_ACTIVE_CODE_EXPIRED = 'ERR_ACTIVE_CODE_EXPIRED';

// 验证码错误
export const ERR_ACTIVE_CODE_INVALID = 'ERR_ACTIVE_CODE_INVALID';

// 账户不存在
export const ERR_ACCOUNT_NOT_FOUND = 'ERR_ACCOUNT_NOT_FOUND';

// 账户已激活
export const ERR_ACCOUNT_REPEATED_ACTIVATION_DETECTED =
  'ERR_ACCOUNT_REPEATED_ACTIVATION_DETECTED';
